# Overrides on top of detekt's default config (buildUponDefaultConfig = true).
naming:
  FunctionNaming:
    ignoreAnnotated: ['Composable']

complexity:
  LongParameterList:
    ignoreAnnotated: ['Composable']
  TooManyFunctions:
    ignoreAnnotated: ['Composable']

style:
  UnusedPrivateMember:
    ignoreAnnotated: ['Preview']
  MagicNumber:
    ignoreAnnotated: ['Composable', 'Preview']
    ignorePropertyDeclaration: true
